### ISSUE TITLE
Sort by day automatically when using custom query

### ISSUE THREAD

**Issue by pjaudiomv** [radius314/yap#168]
**Describe the solution you'd like**
With the new custom query feature, it would be nice and make sense to automatically sort the results by current day. Ref #11

**Comment by radius314** [comment]
It's always going to do this.

**Comment by pjaudiomv** [comment]
yes I believe it should. makes sense to me.

**Comment by pjaudiomv** [comment]
cool, this is working now.

**Comment by radius314** [comment]
it's possible in the case of a custom_query that you will not gather / require location information.  for example in the island use case you just are retrieving the service body.  

in this scenario, there is no way to know what day it is because there is no timezone information.  instead what will happen is it will look at the first meeting result to determine the lat/long and use that to assume the timezone.

**Comment by pjaudiomv** [comment]
i saw that, neat!

**Comment by radius314** [comment]
a further enhancement here could be to look at the meetings for today and apply the grace period logic and shove those to the end of the array, since they are now the furthest away (this makes the assumption that there is only a 4th dimension and time is linear)

**Comment by radius314** [comment]
*those that have passed

**Comment by pjaudiomv** [comment]
ah yes that would be, island use case not needed. but see where it could be useful.

**Comment by radius314** [comment]
released with 2.5.0
